data:extend({
  {
    type = "int-setting",
    name = "ltn-interface-log-level",
    setting_type = "runtime-global",
    default_value = 2,
    maximum_value = 4,
    minimum_value = 0,
    per_user = false,
  },
  {
    type = "string-setting",
    name = "ltn-interface-log-output",
    setting_type = "runtime-global",
    default_value = "both",
    allowed_values = {"both", "console", "log"},
    per_user = false,
  },
  {
    type = "int-setting",
    name = "ltn-interface-message-filter-age",
    setting_type = "runtime-global",
    default_value = 18000,
    minimum_value = 0,
    per_user = false,
  },
  {
    type = "int-setting",
    name = "ltn-dispatcher-update-interval",
    setting_type = "runtime-global",
    default_value = 60,
    minimum_value = 2,
    per_user = false,
  },
  {
    type = "int-setting",
    name = "ltn-dispatcher-min-delivery-size",
    setting_type = "runtime-global",
    default_value = 1000,
    minimum_value = 1,
    per_user = false,
  },

  {
    type = "int-setting",
    name = "ltn-dispatcher-stop-timeout",
    setting_type = "runtime-global",
    default_value = 7200,
    minimum_value = 0,
    per_user = false,
  },
  {
    type = "int-setting",
    name = "ltn-dispatcher-delivery-timeout",
    setting_type = "runtime-global",
    default_value = 18000,
    minimum_value = 3600,
    per_user = false,
  },
  {
    type = "bool-setting",
    name = "ltn-dispatcher-finish-loading",
    setting_type = "runtime-global",
    default_value = true,
    per_user = false,
  },
  {
    type = "bool-setting",
    name = "ltn-dispatcher-use-best-effort",
    setting_type = "runtime-global",
    default_value = false,
    per_user = false,
  },
})